export const DatosProspectos = [
  {
    id: "1",
    nombre: "Juan Peres",
    medio: "WhatsApp",
    programa: "Marketing Digital",
    modalidad: "Virtual",
    fechaRegistro: "20/01/2023",
    estado: "INTERESADO",
    correo: "juan@hotmail.com",
    tipo: "Diplomados",
  },
  {
    id: "2",
    nombre: "Martin Ris",
    medio: "Facebook",
    programa: "Programacion",
    modalidad: "Presencial",
    fechaRegistro: "20/01/2023",
    estado: "PAGADO",
    correo: "mar@hotmail.com",
    tipo: "Curso",
  },
  {
    id: "3",
    nombre: "Lucas Ris",
    medio: "Web",
    programa: "Sales Support",
    modalidad: "Presencial",
    fechaRegistro: "20/01/2023",
    estado: "LISTA NEGRA",
    correo: "lucas@hotmail.com",
    tipo: "Diplomas",
  },
  {
    id: "4",
    nombre: "Pepe luchgo",
    medio: "Zoom",
    programa: "System Developers",
    modalidad: "Virtual",
    fechaRegistro: "31/01/2023",
    estado: "PAGADO",
    correo: "pepe@hotmail.com",
    tipo: "Curso",
  },
  {
    id: "5",
    nombre: "Bentin Romano",
    medio: "Facebook",
    programa: "SIAF",
    modalidad: "Presencial",
    fechaRegistro: "28/01/2023",
    estado: "NO CONTESTA",
    correo: "Betin@hotmail.com",
    tipo: "Diplomas",
  },
  {
    id: "6",
    nombre: "Julio Cesar",
    medio: "WhatsApp",
    programa: "Programacion",
    modalidad: "Presencial",
    fechaRegistro: "27/01/2023",
    estado: "PAGADO",
    correo: "Julio@hotmail.com",
    tipo: "Diplomados",
  },
  {
    id: "7",
    nombre: "David Martinez",
    medio: "Web",
    programa: "System Developer",
    modalidad: "Virtual",
    fechaRegistro: "26/01/2023",
    estado: "INTERESADO",
    correo: "David@hotmail.com",
    tipo: "Curso",
  },
  {
    id: "8",
    nombre: "Don Will",
    medio: "Zoom",
    programa: "Diseño Grafico",
    modalidad: "Virtual",
    fechaRegistro: "28/01/2023",
    estado: "PAGADO",
    correo: "Will@hotmail.com",
    tipo: "Diplomas ",
  },
  {
    id: "9",
    nombre: "Yessica Rivera",
    medio: "Web",
    programa: "Chef",
    modalidad: "Presencial",
    fechaRegistro: "25/01/2023",
    estado: "PAGADO",
    correo: "Yessica@hotmail.com",
    tipo: "Curso",
  },
  {
    id: "10",
    nombre: "Elisa Gutierrez",
    medio: "Facebook",
    programa: "Contabilidad",
    modalidad: "Presencial",
    fechaRegistro: "20/01/2023",
    estado: "INTERESADA",
    correo: "elisa@hotmail.com",
    tipo: "Diplomas",
  },
    {
    id: "11",
    nombre: "Sara Lopez",
    medio: "WhatsApp",
    programa: "Psicologia",
    modalidad: "Virtual",
    fechaRegistro: "18/01/2023",
    estado: "INTERESADA",
    correo: "sara@hotmail.com",
    tipo: "Curso",
  },
];
